version: "2"
services:
  rest-api:
    build: .
    environment:
      - MONGO_URI=mongodb://127.0.0.1:27018/rest_api
    volumes:
      - .:/app
    ports:
      - "4000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27018:27017"

